name: Run Migrations

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # adjust if needed

    - name: Install dotnet-ef
      run: dotnet tool install --global dotnet-ef

    - name: Add dotnet tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      run: dotnet restore ./SensoringAPI/SensoringAPI.csproj

    - name: Run EF Core Migrations
      run: dotnet ef database update --connection "${{ secrets.DB_CONNECTION_STRING }}" --project ./SensoringAPI --startup-project ./SensoringAPI
      env:
        DOTNET_ENVIRONMENT: Production
